# Generated by Django 5.2.7 on 2025-11-13 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.department'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.department'),
        ),
        migrations.RemoveField(
            model_name='subject',
            name='department',
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='students', to='academics.subject'),
        ),
        migrations.DeleteModel(
            name='AssignedSubjects',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
