# Generated by Django 5.2.7 on 2025-11-13 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_teacherprofile_department_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherprofile',
            old_name='department',
            new_name='course',
        ),
    ]
