# Generated by Django 5.2.7 on 2025-11-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_first_login_teacherprofile_middle_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentprofile',
            name='name',
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='first_name',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='last_name',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='middle_name',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
