# Generated by Django 5.2.7 on 2025-11-13 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0003_rename_department_teacherprofile_course'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Department',
            new_name='Course',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='department',
            new_name='course',
        ),
    ]
