# Generated by Django 5.2.7 on 2025-11-15 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectoffering',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.teacherprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('subject_code', 'semester_number')},
        ),
        migrations.AlterUniqueTogether(
            name='subjectoffering',
            unique_together={('subject', 'semester', 'school_year', 'year')},
        ),
    ]
