# Generated by Django 5.2.7 on 2025-11-19 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subjectoffering',
            unique_together={('subject', 'school_year', 'year')},
        ),
        migrations.RemoveField(
            model_name='subjectoffering',
            name='semester',
        ),
    ]
