# Generated by Django 5.2.7 on 2025-11-27 16:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
